### PR TITLE
BookStore: Use-Redux-in-React-Components

### PR DESCRIPTION
**Pull request by Kumilachew-g**
**In this PR, I have done the following tasks.**

-   I have changed the default state in my books reducer from an empty array to an array with a few books.
- I have imported **Redux Provider** and my store into the main component of your React app.
- I have connected my app to the Redux store.
- I have checked that list of books displayed from the Redux store using **useSelector** to consume the state.
- I have imported **useDispatch** and used it to add and remove functionalities, and to check status.
**UI Looks like:**  
image

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
## Hi @Kumilachew-g,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Your categories page should contain a button that when clicked dispatches an action to the store and returns the "Under construction" message. Kindly do that.

  cs

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kumilachew-g** [comment]
Sorry @julie-ify,  I don't understand what you saying. Kindly clone and check it.  It works like this as you said.
image

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @Kumilachew-g, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅  
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by victorokoroji** [comment]
@Kumilachew-g This PR is Approved ✔️

**Pull request merged**
